## **ASSIGNMENT 1**
# Instructor: Gianfranco Doretto
# Due: September 15, 2022 by the beginning of the lecture
# Student Name: Ali Zafari

The assignment is composed of two sections. The first one is made of simple programmng questions that require you to use Python. The second section requires you to implement and test two image processong algorithms.

If you are new to Colab, Python Numpy, and so on, you are strongly encouraged to read [this tutorial](https://cs231n.github.io/python-numpy-tutorial/). 

**Submission Instructions**

You will need to prepare a folder called

```hw1_YOUR-LAST-NAME_YOUR-FIRST-NAME```

In that folder you want to put
- Your Colab notebook (fill out the Student Name above)
- For every question that requires submitting data you create a subfolder called ```question_NUMBER``` and you put there the files with adequate naming. If we do not understand that something is there you will not get credit!

You will need to zip the folder and you will need to submit the zip file ```hw1_YOUR-LAST-NAME_YOUR-FIRST-NAME.zip``` to the instructor by sharing the file via Google Drive.

In order to [share a file](https://support.google.com/drive/answer/2494822?hl=en&co=GENIE.Platform%3DDesktop) with the instructor please use this email gidoretto@mix.wvu.edu

During the evaluation we are going to test your Python notebook with Google Colab. So, the assumption is that you are going to do all the development with Colab. We will run your notebook by running the cells sequentially. They will have to produce the expected result in order for you to get credit.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# *Exercise 1*
This is a Python Numpy wormup exercise. Complete each of the functions below as descibed by the Input/Returns requirements. Below each function add a code cell, and write in it just a few lines of code to show that your function works.
Every function should be implementable with only **one** line of code.

For example, this function:
```python
def f0(X):
    """
    Input:
    - X: A numpy array

    Returns:
    - A matrix Y such that Y[i, j] = X[i, j] * 10 + 100

    Hint: Trust that numpy will do the right thing
    """
    return None
```
Should be completed as
```python
def f0(X):
    """
    Input:
    - X: A numpy array

    Returns:
    - A matrix Y such that Y[i, j] = X[i, j] * 10 + 100

    Hint: Trust that numpy will do the right thing
    """
    return X*10+100
```
An example of code that tests ```f0``` could be
```python
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(x)
print(f0(x))
```

In [2]:
import numpy as np

In [3]:
def f1(X, Y):
    """
    Inputs:
    - X: A numpy array of shape (N, N)
    - Y: A numpy array of shape (N, N)

    Returns:
    A numpy array Z such that Z[i, j] = X[i, j] + 10 * Y[i, j]

    Hint: Trust that numpy will do the right thing
    """
    return X + 10 * Y

Add a code cell below with just enough lines that show that your function works.

In [4]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[4, 3], [2, 1]])

print(f'x:\n {x}')
print(f'y:\n {y}')
print(f'f1:\n {f1(x, y)}')

x:
 [[1 2]
 [3 4]]
y:
 [[4 3]
 [2 1]]
f1:
 [[41 32]
 [23 14]]


In [5]:
def f2(X, Y):
    """
    Inputs:
    - X: A numpy array of shape (N, N)
    - Y: A numpy array of shape (N, N)

    Returns:
    A numpy array Z such that Z[i, j] = X[i, j] * Y[i, j] - 10

    Hint: By analogy to +, * will do the same thing
    """
    return X * Y - 10

Add a code cell below with just enough lines that show that your function works.

In [6]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[4, 3], [2, 1]])

print(f'x:\n {x}')
print(f'y:\n {y}')
print(f'f2:\n {f2(x, y)}')

x:
 [[1 2]
 [3 4]]
y:
 [[4 3]
 [2 1]]
f2:
 [[-6 -4]
 [-4 -6]]


In [7]:
def f3(X):
    """
    Inputs:
    - X: A numpy array of shape (N, N) of floating point numbers

    Returns:
    A numpy array with the same data as X, but cast to 32-bit integers

    Hint: astype
    """
    return X.astype(np.int32)

Add a code cell below with just enough lines that show that your function works.

In [8]:
x = np.array([[1, 2], [3, 4]], dtype=np.float16)
y = f3(x)
print(f'x.dtype: {x.dtype}')
print(f'f3.dtype: {y.dtype}')

x.dtype: float16
f3.dtype: int32


In [9]:
def f4(X):
    """
    Inputs:
    - X: A numpy array of shape (N, M)

    Returns:
    - A numpy array Y of shape (N * M, 1) containing the entries of X in row
      order. That is, X[i, j] = Y[i * M + j, 0]

    Hint:
    1) np.reshape
    2) You can specify an unknown dimension as -1
    """
    return X.reshape(-1, 1)


Add a code cell below with just enough lines that show that your function works.

In [10]:
x = np.array([[1, 2], [3, 4], [5, 6]])
y = f4(x)
print(f'x.shape: {x.shape}')
print(f'y.shape: {y.shape}')

x.shape: (3, 2)
y.shape: (6, 1)


Add a code cell below with just enough lines that show that your function works.


In [11]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
y = f4(x)
print(f'x.shape: {x.shape}')
print(f'f4.shape: {y.shape}')

x.shape: (2, 5)
f4.shape: (10, 1)


In [12]:
def f5(X):
    """
    Inputs:
    - X: A numpy array of shape (N, M) where each entry is between 0 and 1

    Returns:
    A numpy array Y where Y[i, j] = True if X[i, j] > 0.5

    Hint: Trust python to do the right thing
    """
    return X > 0.5

Add a code cell below with just enough lines that show that your function works.


In [13]:
x = np.array([[0.1, 0.7], [0.9, 1], [0, 0.6]])
y = f5(x)
print(f'x:\n {x}')
print(f'f5:\n {y}')

x:
 [[0.1 0.7]
 [0.9 1. ]
 [0.  0.6]]
f5:
 [[False  True]
 [ True  True]
 [False  True]]


In [14]:
def f6(A, v):
    """
    Inputs:
    - A: A numpy array of shape (N, F)
    - v: A numpy array of shape (F, 1)

    Returns:
    Numpy array of shape (N, 1) giving the matrix-vector product Av
    """
    return np.matmul(A, v)

Add a code cell below with just enough lines that show that your function works.

In [15]:
A = np.array([[1, 2], [3, 4]])
v = np.array([[2], [3]])
print(f'A:\n {A}')
print(f'v:\n {v}')
print(f'f6:\n {f6(A, v)}')

A:
 [[1 2]
 [3 4]]
v:
 [[2]
 [3]]
f6:
 [[ 8]
 [18]]


Add a code cell below with just enough lines that show that your function works.

In [16]:
A = np.array([[1, 0], [0, 2]])
v = np.array([[1], [-1]])
print(f'A:\n {A}')
print(f'v:\n {v}')
print(f'f6:\n {f6(A, v)}')

A:
 [[1 0]
 [0 2]]
v:
 [[ 1]
 [-1]]
f6:
 [[ 1]
 [-2]]


In [17]:
def f7(v):
    """
    Inputs:
    - v: A numpy array of shape (N, 1)

    Returns:
    The L2 norm of v: norm = (sum_i^N v[i]^2)^(1/2)
    You MAY NOT use np.linalg.norm
    """
    return np.sqrt(np.sum(np.square(v)))

Add a code cell below with just enough lines that show that your function works.



In [18]:
v = np.array([[6], [8]])
print(f'v:\n {v}')
print(f'f7:\n {f7(v)}')

v:
 [[6]
 [8]]
f7:
 10.0


In [19]:
def f8(X):
    """
    Inputs:
    - X: A numpy array of shape (N, M)

    Returns:
    The sum of all entries in X

    Hint: np.sum
    """
    return np.sum(X)

Add a code cell below with just enough lines that show that your function works.



In [20]:
X = np.array([[1, -2], [3, 4]])
print(f'X:\n {X}')
print(f'f8:\n {f8(X)}')

X:
 [[ 1 -2]
 [ 3  4]]
f8:
 6


In [21]:
def f9(X):
    """
    Inputs:
    - X: A numpy array of shape (N, M)

    Returns:
    A numpy array S of shape (M,) where S[j] is the sum of column j of X

    Hint: np.sum has an optional "axis" argument
    """
    return np.sum(X, axis=0)

Add a code cell below with just enough lines that show that your function works.



In [22]:
X = np.array([[1, -3], [3, 4]])
print(f'X:\n {X}')
print(f'f9:\n {f9(X)}')

X:
 [[ 1 -3]
 [ 3  4]]
f9:
 [4 1]


In [23]:
def f10(X):
    """
    Inputs:
    - X: A numpy array of shape (N, M)

    Returns:
    A numpy array S of shape (N, 1) where S[i] is the L2 norm of row i of X
    """
    return np.sqrt(np.sum(np.square(X), axis=1)).reshape(-1, 1)

Add a code cell below with just enough lines that show that your function works.




In [24]:
X = np.array([[3, 4], [6, 8], [9, 12]])
print(f'X:\n {X}')
print(f'f10:\n {f10(X)}')

X:
 [[ 3  4]
 [ 6  8]
 [ 9 12]]
f10:
 [[ 5.]
 [10.]
 [15.]]


# *Exercise 2*
This is a Python Numpy exercise. Complete each of the functions below as descibed by the Input/Returns requirements. Below each function add a code cell, and write in it just a few lines of code to show that your function works.
These functions may require you to write more than one line of code. The instructions will indicate what is the expected number of lines. You might be able to write fewer lines, but you should not exceed the maximum number of lines indicated. __You are not allowed to use the ```for``` loop construct__.


In [25]:
import numpy as np

In [26]:
def g1(L):
    """
    Inputs:
    - L: A list of M numpy arrays, each of shape (1, N)

    Returns:
    A numpy array of shape (M, N) giving all inputs stacked together

    Lines of code: 1

    Hint: vstack/hstack/dstack, no for loop
    """
    return np.vstack(L)

Add a code cell below with just enough lines that show that your function works.


In [27]:
L = [np.array([[1, 2, 3, 4]]), np.array([[5, 6, 7, 8]])]
print(f'L:\n{L} \n\n L[0].shape:\n{L[0].shape} \n L[1].shape:\n{L[1].shape}\n')
print(f'g1(L):\n{g1(L)},\n\ng1(L).shape:\n{g1(L).shape}')

L:
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])] 

 L[0].shape:
(1, 4) 
 L[1].shape:
(1, 4)

g1(L):
[[1 2 3 4]
 [5 6 7 8]],

g1(L).shape:
(2, 4)


In [28]:
def g2(X):
    """
    Inputs:
    - X: A numpy array of any shape

    Returns:
    A copy of X, but with all negative entires set to 0

    Lines of code: 2-3

    Hint:
    1) If S is a boolean array with the same shape as X, then X[S] gives an
       array containing all elements of X corresponding to true values of S
    2) X[S] = v assigns the value v to all entires of X corresponding to
       true values of S.
    """
    newX = X.copy()
    newX[newX < 0] = 0
    return newX

Add a code cell below with just enough lines that show that your function works.


In [29]:
X = np.array([[3, -4], [0, 8], [9, -0.1]])
print(f'X:\n {X}')
print(f'g2:\n {g2(X)}')

X:
 [[ 3.  -4. ]
 [ 0.   8. ]
 [ 9.  -0.1]]
g2:
 [[3. 0.]
 [0. 8.]
 [9. 0.]]


In [30]:
def g3(X):
    """
    Inputs:
    - X: A numpy array of shape (N, N)

    Returns:
    A numpy array of shape (4, 4) giving the upper left 4x4 submatrix of X
    minus the bottom right 4x4 submatrix of X.

    Lines of code: 1-2

    Hint:
    1) X[y0:y1, x0:x1] gives the submatrix
       from rows y0 to (but not including!) y1
       from columns x0 (but not including!) x1
    """
    return X[0:4, 0:4] - X[np.ix_(np.arange(-4, 0), np.arange(-4, 0))]

Add a code cell below with just enough lines that show that your function works.


In [31]:
X = np.random.randint(1, 5, size=(10, 10))
print(f'X:\n{X}')
print(f'g3(X):\n{g3(X)}')

X:
[[3 2 2 3 4 4 1 4 4 4]
 [4 1 4 4 3 3 3 4 2 3]
 [3 1 2 2 4 3 4 1 1 3]
 [1 3 1 4 2 4 2 3 4 1]
 [2 1 4 1 2 4 2 2 3 3]
 [1 2 2 2 3 1 4 1 4 4]
 [3 4 1 3 2 1 2 3 3 2]
 [1 4 1 2 2 3 3 3 1 4]
 [2 3 1 4 2 2 3 3 2 1]
 [3 3 3 2 2 4 4 4 1 3]]
g3(X):
[[ 1 -1 -1  1]
 [ 1 -2  3  0]
 [ 0 -2  0  1]
 [-3 -1  0  1]]


In [32]:
def g4(X):
    """
    Inputs:
    - X: A numpy array of shape (N, M)

    Returns:
    A numpy array Y of the same shape as X, where Y[i] is a vector that points
    the same direction as X[i] but has unit norm.

    Lines of code: 1-3

    Hints:
    1) The vector v / ||v||| is the unit vector pointing in the same direction
       as v (as long as v != 0)
    2) Divide X by a vector of normalization factors, of shape (N, 1)
    3) Elementwise operations between an array of shape (N, M) and an array of
       shape (N, 1) work -- try it! This is called "broadcasting"
    4) Elementwise operations between an array of shape (N, M) and an array of
       shape (N,) won't work -- try reshaping
    """
    return X / np.sqrt(np.sum(np.square(X), axis=1, keepdims=True))


Add a code cell below with just enough lines that show that your function works.


In [33]:
X = np.array([[4, 7, 6, 7],[1, 4, 2, 2],[7, 1, 1, 5]])
print(f'X:\n{X}')
print(f'g4(X):\n{g4(X)}')

X:
[[4 7 6 7]
 [1 4 2 2]
 [7 1 1 5]]
g4(X):
[[0.32659863 0.57154761 0.48989795 0.57154761]
 [0.2        0.8        0.4        0.4       ]
 [0.80295507 0.11470787 0.11470787 0.57353933]]


In [34]:
def g5(q, k, v):
    """
    Inputs:
    - q: A numpy array of shape (1, K) (queries)
    - k: A numpy array of shape (N, K) (keys)
    - v: A numpy array of shape (N, 1) (values)

    Returns:
    sum_i exp(-||q-k_i||^2) * v[i]

    Lines of code: 1-3

    Hints:
    1) You can perform elementwise operations on arrays of shape (N, K) and
       (1, K) with broadcasting
    2) Recall that np.sum has useful "axis" and "keepdims" options
    3) np.exp and friends apply elementwise to arrays
    """
    return np.dot(np.exp(-np.sum(np.square(q-k), axis=1)), v.squeeze())

Add a code cell below with just enough lines that show that your function works.


In [35]:
q = np.array([[1, 2, 3]])
k = np.array([[0, 1, 2], [4, 5, 6]])
v = np.array([[7, 8]])

print(f'q:\n{q}')
print(f'k:\n{k}')
print(f'v:\n{v}')
print(f'\ng5(q, k, v):\n{g5(q, k, v)}')

q:
[[1 2 3]]
k:
[[0 1 2]
 [4 5 6]]
v:
[[7 8]]

g5(q, k, v):
0.34850947859008385


In [36]:
def g6(X):
    """
    Inputs:
    - X: A numpy array of shape (N, M)

    Returns:
    A numpy array D of shape (N, N) where D[i, j] gives the Euclidean distance
    between X[i] and X[j], using the identity
    ||x - y||^2 = ||x||^2 + ||y||^2 - 2x^T y

    Line of code: 2-3

    Hints:
    1) What happens when you add two arrays of shape (1, N) and (N, 1)?
    2) Think about the definition of matrix multiplication
    3) Transpose is your friend
    4) Note the square! Use a square root at the end
    5) On some machines, ||x||^2 + ||x||^2 - 2x^Tx may be slightly negative,
       causing the square root to crash. Just take max(0, value) before the
       square root. Seems to occur on Macs.
    """
    y = np.sum(np.square(X), axis=1, keepdims=True)
    z = np.matmul(X, X.T)
    return np.sqrt(y + y.T - 2 * z)

Add a code cell below with just enough lines that show that your function works.


In [37]:
X = np.array([[1, 2, 3], [4, 5, 6]])
print(f'X:\n{X}')
print(f'g6(X):\n{g6(X)}')

X:
[[1 2 3]
 [4 5 6]]
g6(X):
[[0.         5.19615242]
 [5.19615242 0.        ]]


In [38]:
def g7(q, V):
    """
    Inputs:
    - q: A numpy array of shape (1, M) (query)
    - V: A numpy array of shape (N, M) (values)

    Return:
    The index i that maximizes the dot product q . V[i]

    Lines of code: 1

    Hint: np.argmax
    """
    return np.argmax(np.dot(V, q.T))


Add a code cell below with just enough lines that show that your function works.


In [39]:
q = np.array([[1, 2, 3]])
V = np.array([[1, 1, 1], [-1, 1, 1]])
print(f'q:\n {q}')
print(f'V:\n {V}')
print(f'\ng7(q, V): {g7(q, V)}')

q:
 [[1 2 3]]
V:
 [[ 1  1  1]
 [-1  1  1]]

g7(q, V): 0


In [40]:
def g8(X, Y):
    """
    Inputs:
    - X: A numpy array of shape (N, 3)
    - Y: A numpy array of shape (N, 3)

    Returns:
    A numpy array C of shape (N, 3) such C[i] is the cross product between X[i]
    and Y[i]

    Lines of code: 1

    Hint: np.cross
    """
    return np.cross(X, Y)



Add a code cell below with just enough lines that show that your function works.


In [41]:
X = np.array([[1,2,3], [4,5,6]])
Y = np.array([[4,5,6], [1,2,3]])
print(f'X:\n {X}')
print(f'Y:\n {Y}')
print(f'g8(X, Y):\n {g8(X, Y)}')

X:
 [[1 2 3]
 [4 5 6]]
Y:
 [[4 5 6]
 [1 2 3]]
g8(X, Y):
 [[-3  6 -3]
 [ 3 -6  3]]


In [42]:
def g9(X):
    """
    Inputs:
    - X: A numpy array of shape (N, M)

    Returns:
    A numpy array Y of shape (N, M + 1) such that
        Y[i, :F] = X[i]
        Y[i, F] = 1

    Lines of code: 1

    Hint: np.hstack, np.ones
    """
    return np.hstack([X, np.ones((X.shape[0], 1))])

Add a code cell below with just enough lines that show that your function works.


In [43]:
X = np.random.randint(1, 10, size=(7, 3))
print(f'X:\n {X}')
print(f'g9(X):\n {g9(X)}')

X:
 [[8 7 2]
 [6 3 1]
 [2 2 1]
 [7 9 8]
 [1 8 6]
 [6 2 7]
 [1 9 2]]
g9(X):
 [[8. 7. 2. 1.]
 [6. 3. 1. 1.]
 [2. 2. 1. 1.]
 [7. 9. 8. 1.]
 [1. 8. 6. 1.]
 [6. 2. 7. 1.]
 [1. 9. 2. 1.]]


In [44]:
def g10(N, s, x, y):
    """
    Inputs:
    - N: An integer
    - s: A floating-point number
    - x: A floating-point number
    - y: A floating-point number

    Returns:
    A numpy array I of shape (N, N) such that
    I[i, j] = exp(-||(j, i) - (x, y)||^2 / s^2)

    Lines of code: 2-3

    Hint: Be careful with types -- float and int aren't the same!
    """
    I = np.indices((N, N)).transpose(1, 2, 0)
    return np.exp(-np.sum(np.square(I-np.array([x, y])), axis=2)/s**2)

Add a code cell below with just enough lines that show that your function works.


In [45]:
N = 5
s = 0.5
x = 0.25
y = 1.75

print(f'g10(N, s, x, y):\n {g10(N, s, x, y)}')

g10(N, s, x, y):
 [[3.72665317e-06 8.20849986e-02 6.06530660e-01 1.50343919e-03
  1.25015287e-09]
 [5.04347663e-07 1.11089965e-02 8.20849986e-02 2.03468369e-04
  1.69189792e-10]
 [2.28973485e-11 5.04347663e-07 3.72665317e-06 9.23744966e-09
  7.68120469e-15]
 [3.48726153e-19 7.68120469e-15 5.67568523e-14 1.40686171e-16
  1.16984592e-22]
 [1.78167296e-30 3.92439586e-26 2.89975811e-25 7.18778174e-28
  5.97684694e-34]]


# *Exercise 3*

In this exercise you are going to experiment with image quantization. 

You have been given two folders with images. The folder ```images``` contains a gallery of 10 images. The folder ```images_200``` contains the same images but resized with the biggest dimension to not exceed 200 pixels. Initially, you will operate on the folder with the smaller images because the algorithms you will implement will be relatively slow, and will take a lot of time if made them to work on the images with original size. Also, you will convert the images to grayscale.

Later in the exercise, you will implement a resizing function that will allow you to operate at the desired resolution, and you will also extend the algorithms to handle colors.

The idea of image quantization is that the 256 levels used to represent each color channel or the intensity (if the image is grayscale), have to be mapped according to a uniform palette, obtained by setting the number of bits per color channel that you use. To encode the original 256 levels, 8 bits are necessary. To encode in 2 levels only 1 bit is necessary.

In this exercise you will be concerned to mainly generate quantization results based on 1 bit and on 2 bits.

In principle, encoding an image with less bits per pixel allows to represent it more efficiently, and it enables its display in mediums that have a limited palette. One example is the [GIF](https://en.wikipedia.org/wiki/GIF) image format, which allows a palette of only 256 colors, as opposed to the full range of colors of a 24-bits image.  

In [46]:
import os
import sys
import cv2
import numpy as np

def coverPalette(N):
    # Return the palette we're using
    return np.linspace(1, 0, 2 ** N)

def reconstructImage(IQ, palette):
    """
    Given a quantized image IQ and their value, return a floating point image
    """
    # opencv is full of these assertions.
    # If you're looking here you may have an error.
    # Check to see what the assertion says
    assert(np.issubdtype(IQ.dtype, np.integer))
    return palette[IQ]

def upscaleNN(I, target_size):
    """
    NN upsample I until it hits a target size but without going over 4096
    """
    h, w = I.shape[:2]
    scale = 1
    while True:
        if min(h * scale, w * scale) >= target_size:
            break
        if max(h * (scale + 1), w * (scale + 1)) > 4096:
            break
        scale += 1
    # usually you should call a library but providing the call here defeats
    # the purpose :)
    shape = (scale, scale) if I.ndim == 2 else (scale, scale, 1)
    return np.kron(I, np.ones(shape))


In [47]:
coverPalette(1)

array([1., 0.])

The code cell below is where you are supposed to write almost all the code. You need to complete the two quantization algorithms ```quantizeNaive``` and ```quantizeFloyd```, and a utility function ```quantize``` to be used by the algorithms.

Every quantization algorithm has the following Input/Output specification:
- **Input:** (a) a $H\timesW$ floating point image with brightness ranging from 0 to 1, and (b) a palette consisting of all the $K$ allowed brightness settings (which are floats in the range 0 to 1).
- **Output:** each algorithm produces a $H\times W$ ```uint8``` image with brightness ranging from $0$ to
$K-1$. This is the quantized image. We can use the quantized image and the palette to compute a reconstructed image, and this is done by the  function ```reconstructImage```.



**Naive Quantization**

Begin by implementing ```quantize(v,palette)```. This should return the index of the nearest value in the palette to the single value ```v```. Do not use a ```for``` loop. You can look at functions like ```np.argmin```. If you find another way that is more clever, feel free to propose it.

Implement ```quantizeNaive(IF,palette)```. This approach aims at approximating the image by quantizing each pixel with the closest value in the palette. Therefore, ```quantizeNaive(IF,palette)``` takes a floating point image of size $H\times W$ and a palette of values, and creates a new ```uint8``` image  and uses ```quantize()``` to find the index of the nearest pixel. It returns the $H\times W$ ```uint8``` image of the palette indices.

**Question 1.** When you run the quantization on the full set of images in ```images_200```, in one sentence say why might your code take a very long time.

**Question 2.** For 1 and then for 2 bits per pixel, embed (show) in the cell below three results of inputs and outputs. Also, make sure you save the same images in the appropriate folder because you will need to submit them.

**How to embed images in Colab:** From your Google Drive navigate to the file, and by right-clicking on it select Get Link. Now change the option from "Restricted" to "Anyone with the link" and copy the link. You will get a link like this

```https://drive.google.com/file/d/1Ljc932JoNfmChw_CvDBbogfyht8wakIZ/view?usp=sharing```

You want to get the ID of the file:

```1YZPSVXP8s6FpkpuCSJdBymhRhfDiac58```

and put it in front of 

```https://drive.google.com/uc?id=```

to obtain the final link

```https://drive.google.com/uc?id=1Ljc932JoNfmChw_CvDBbogfyht8wakIZ```

Now you can embed the image by using ```![](link)```
This is how it is done here:

![](https://drive.google.com/uc?id=1Ljc932JoNfmChw_CvDBbogfyht8wakIZ)



**Answer to Question 1:**
Time complexity of O(n^2) slows down our algorithm when the dimensions of image gets larger.


**Answer to Question 2:**

|Original|Naive 1 bit|Naive 2 bit|
|-|-|-|
![x](https://drive.google.com/uc?id=109XvHZi9_Lu15ABPBb9PPXRZkU3d71es)|![x](https://drive.google.com/uc?id=114We1saCDSDO2ocK6Bhtx7mWVhhmYqPd)|![x](https://drive.google.com/uc?id=11ZaCz6xSspF1JQPhSNb7RoUMEZ27wrFs)|
||||
![x](https://drive.google.com/uc?id=10EvUtGO-tfDFvn6JhDTO0ZW2UOukYWqf)|![x](https://drive.google.com/uc?id=10u-B5de4dSL2l2DKZA4c3boig21Uk0gh)|![x](https://drive.google.com/uc?id=11W-dSIm5TjtGriqmgbDlzR1LCPbawzwc)|
||||
![x](https://drive.google.com/uc?id=10hfnN60DPVQdtYA71a2N_q1RAcd80ipw)|![x](https://drive.google.com/uc?id=11Dhp4fe4zGevH2bw7IzrmTN1KdwEW1oR)|![x](https://drive.google.com/uc?id=11tIUZMhbb0ZI4AsvqkwPh7LTwHjFJ4KH)|

**Floyd Quantization**

To improve upon the naive quantization, you will implement the [Floyd–Steinberg dithering](https://en.wikipedia.org/wiki/Floyd–Steinberg_dithering) algorithm in the function ```quantizeFloyd```.
The pseudocode from Wikipedia is summarized below:
```python
output = new HxW that indexes into the palette
for y in range(H): for x in range(W):
  oldValue = pixel[x][y]
  colorIndex = quantize(oldValue,palette)
  output[x][y] = colorIndex
  newValue = palette[colorIndex]
  error = oldValue-newValue
  pixel[x+1][y] += error*7/16
  pixel[x-1][y+1] += error*3/16
  pixel[x][y+1] += error*5/16
  pixel[x+1][y+1] += error*1/16
return Output
```
In your implementation you want to pay attention to a few important things. For instance, depending on the libraries you are using, the way in which a pixel is indexed changes, because they will make different assumptions about whether x or y come first. As you implement the algorithm there will be edge cases, and you might need to define what behavior to follow. Finally, be careful about how data is passed to the function. In order to produce the output, you will need to change the values of ```IF```. You may need to make an internal copy of it (```IF.copy()```), if necessary, since you do not want to change the data you were given as input.

**Question 3.** Explain briefly why the Floyd quantization does a better job than the naive version.

**Question 4.** For 1 and then for 2 bits per pixel, embed (show) in the cell below three results of inputs and outputs. Also, make sure you save the same images because you will need to submit them.


**Answer to Question 3:**
Floyd quantization spreads the quantization error to the futurely to be quntized pixels, so it makes the quantization error to be diffused over the pixels. By doing so, it will increase the probabilty of having downward quantization after a couple of upward quantizations (and vice-versa), finally resulting in lower average quantization error.

**Answer to Question 4:**

|Original|Floyd 1 bit|Floyd 2 bit|
|-|-|-|
![x](https://drive.google.com/uc?id=109XvHZi9_Lu15ABPBb9PPXRZkU3d71es)|![x](https://drive.google.com/uc?id=10KMtywDEkI73Ax1GXZJdr1z5kjku3Qxb)|![x](https://drive.google.com/uc?id=128TFMKKw2JJ3mA3zd-bag2H8ScqJVg2Y)|
||||
![x](https://drive.google.com/uc?id=10EvUtGO-tfDFvn6JhDTO0ZW2UOukYWqf)|![x](https://drive.google.com/uc?id=10EbICC4glaFn62zLPAKgviPrN7M8KVqI)|![x](https://drive.google.com/uc?id=126SMVfweJGbM3nFeHCDQ0nsE3aH6UTht)|
||||
![x](https://drive.google.com/uc?id=10hfnN60DPVQdtYA71a2N_q1RAcd80ipw)|![x](https://drive.google.com/uc?id=10ebzl8xqld1gNymMuY6NY0tj7W83GrMA)|![x](https://drive.google.com/uc?id=12Hv1ZMWBTJRtPeJQd53nZqK4PsgCFT-G)|

In [48]:
def quantize(v, palette):
    """
    Given a scalar v and array of values palette,
    return the index of the closest value
    """
    v = np.atleast_1d(v)[:, np.newaxis]
    palette = palette[:, np.newaxis]
    return np.nanargmin(np.abs(v.T-palette), axis=0)


def quantizeNaive(IF, palette):
    """Given a floating-point image return quantized version (Naive)"""
    _IF = IF.copy()
    for y in range(_IF.shape[0]):
      for x in range(_IF.shape[1]):
        _IF[y, x] = quantize(_IF[y, x], palette)
    return _IF.astype('uint8')


def quantizeFloyd(IF, palette):
    """
    Given a floating-point image return quantized version (Floyd-Steinberg)
    """
    _IF = IF.copy()
    for y in range(_IF.shape[0]):
      for x in range(_IF.shape[1]):
        old_pixel = _IF[y, x].copy()
        new_pixel_palette_index = quantize(old_pixel, palette)
        new_pixel = palette[new_pixel_palette_index]
        _IF[y, x] = new_pixel_palette_index
        quant_error = old_pixel - new_pixel
        if x + 1 < _IF.shape[1]:
          _IF[y, x + 1    ] += quant_error * 7 / 16
        if x - 1 >= 0 and y + 1 < _IF.shape[0]:
          _IF[y + 1, x - 1] += quant_error * 3 / 16
        if y + 1 < _IF.shape[0]:
          _IF[y + 1, x    ] += quant_error * 5 / 16
        if x + 1 < _IF.shape[1] and y + 1 < _IF.shape[0]:
          _IF[y + 1, x + 1] += quant_error * 1 / 16
    return _IF.astype('uint8')

**Image Resizing**

You were given two image folders: ```images```, and ```images_200```. The first folder contains the original images at higher resolution, and the second the same images but with the largest size not bigger than 200 pixels.

You need to implement the function ```resizeImage```. This will allow you to run the algorithms on images with the size you prefer. You can take advantage of the OpenCV function ```cv2.resize```.

In [49]:
def resizeImage(I, maxDim):
    """Given an image, make sure it's no bigger than maxDim on either side"""
    H, W = I.shape[:2]
    newDim = [maxDim, maxDim]
    if H < maxDim:
      newDim[0] = H
    if W < maxDim:
      newDim[1] = W
    return cv2.resize(I, newDim)

**Color Images**

So far your quantozation algorithms have handled grayscale images, now you need to augment them to handle color.

You will need to augment ```quantize(v,palette)``` to handle both a scalar ```v``` and a vector ```v```. In general we can see ```v``` as an n-dimensional vector which will return an n-dimensional vector of palette indices. You can use a for loop, but remember that: (a) broadcasting can take a M-dimensional vector and N-dimensional vector and produce a MxN dimensional matrix; and (b) many functions have an axis
argument.

You will also need to make sure that your version of ```quantizeFloyd(IF,palette)``` can handle images with multiple
channels. Remember that an operation such as ```v = IF[i,j]``` does not copy the value of the color channels, what you get is a reference. So, if you change the data at that reference, this might lead to bugs. You need to make sure you copy the data if necessary.

**Question 5.** For 1 and then for 2 bits per pixel, enbed (show) in the cell below three results of inputs and outputs. Also, make sure you save the same images because you will need to submit them.

**Question 6.** Pick a resolution of your choice, the number of bits of your choiche, and a couple of images of your choice. Generate their dithered versions and embed the inputs and outputs here, and submit them.


**Answer to Question 5:**

|Original|Floyd (RGB) 1 bit|Floyd (RGB) 2 bit|
|-|-|-|
![x](https://drive.google.com/uc?id=12ifzXoakyquYeMvxZAlAxGVwuaoT3qkj)|![x](https://drive.google.com/uc?id=12g8TrnoqDEdWuC_jSbD3YI9Bah5J3Ct_)|![x](https://drive.google.com/uc?id=12mRJhBgjsybZ7Ra1FuJfisw1kYGiTJ1f)|
||||
![x](https://drive.google.com/uc?id=12dWPhAFPuD-Qkn6imd_uEOwbs395Pjd9)|![x](https://drive.google.com/uc?id=12c2jD7ThbQ84lzlcSk4j1gzuIL8K5Zw2)|![x](https://drive.google.com/uc?id=12y3oe-c7OHC41o5ZtOtwcKc2p7iGkkar)|
||||
![x](https://drive.google.com/uc?id=12kr13UHS5Cukoe-FOilZL-UhzdKKLU5M)|![x](https://drive.google.com/uc?id=12k05fs6j54N0m-SpOVqBRM6Lpjf6sNiO)|![x](https://drive.google.com/uc?id=133vo_PZTfHjcceHChkMbXC8lxIqf3A3_)|

**Answer to Question 6:**

|Original|Naive (RGB) 2 bit|Floyd (RGB) 2 bit|
|-|-|-|
![x](https://drive.google.com/uc?id=13dqTq2JB08LD6hGaeFTqPzFqZkW522EB)|![x](https://drive.google.com/uc?id=13oNhEMU7J4GkOIwERFllNnv7B3cjesgi)|![x](https://drive.google.com/uc?id=13dXeE4tFH4FoqUhIhKszwn5VYK2ZNClB)|
||||
![x](https://drive.google.com/uc?id=13cSDDpC1aFnGjYcqYBnBH_q30gxW1kWb)|![x](https://drive.google.com/uc?id=13xUeFOuJ8WE-43z5Yn3R8b-jTRO7f_PO)|![x](https://drive.google.com/uc?id=13VkrImN6ivyQcYnTiW72vcVsHoVIXmUd)|
||||

In [50]:
# Mount your MIX Google Drive
from google.colab import drive
drive_mount = "/content/drive"
drive.mount(drive_mount)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [51]:
# Set the source folder where you have the images
##########################################
# Initially you want to work with the smaller images in images_200
# images_path = "/MyDrive/teaching/cs678/2021 Fall/assignments/assignment1/images_200"
images_path = "/MyDrive/myCV/Assignment1/images"
source = drive_mount+images_path
print(source)
# Load the images and make sure they are ordered
images = [fn for fn in os.listdir(source) if fn.endswith(".jpg")]
images.sort()
print(images)
images = [images[0], images[2]]
print(f'chosen images: {images}')

/content/drive/MyDrive/myCV/Assignment1/images
['IMG_1429.jpg', 'IMG_1740.jpg', 'IMG_1911.jpg', 'IMG_2551.jpg', 'IMG_4644.jpg']
chosen images: ['IMG_1429.jpg', 'IMG_1911.jpg']


In [52]:
# Set the target folder where results will be saved
###################################################
target_path = "/MyDrive/myCV/Assignment1/quantized_images"
target = drive_mount+target_path
if not os.path.exists(target):
  os.mkdir(target)
print(target)

/content/drive/MyDrive/myCV/Assignment1/quantized_images


In [53]:
# Pick the algorithm
####################
# You can pick among [quantizeNaive", "quantizeFloyd" ]
algo_name = "quantizeNaive"
if algo_name not in globals():
  print("I don't recognize that algorithm")
  sys.exit(1)
else:
  quantize_algo = globals()[algo_name]
  print(quantize_algo)

# Pick the number of bits used for representing color
#####################################################
# This will define the palette
# The questions require to use 1 and 2 bits per pixel, but you can 
# experiment with other values
palette = coverPalette(2)
print(palette)

# Pick if the image should be converted to grayscale (True/False)
#################################################################
# Initially you want to convert the images to grayscale
grayscale = False

# Set a target output size different than the input, otherwise set it to 0
##########################################################################
# This can upscale the image. This function could be used to generate images
# that compensate for the number of pixels a display assigns to the
# visualization of one image pixel. 
# If you see the images with a browser with a zoom set to 100% you do not
# need this functionality. Just generate the view.html file below for
# the visualization of results
target_size = 0

# You can resize the input to a new resolution, otherwise set it to 0
#####################################################################
# To use this funcitonality you need to have implemented resizeImage
source_size = 300

<function quantizeNaive at 0x7fad4d5af950>
[1.         0.66666667 0.33333333 0.        ]


In [54]:
# This is the main loop that quantizes the images

# Keep track of heights; we'll need it since we show some small images and
# will otherwise be at the mercy of the webbrowser resize
heights = {}

# for i,value in enumerate(array):
#    --is shorthand for--
# for i in range(len(array)):
#    value = array[i]
for imageI, image in enumerate(images):
  print("%d/%d" % (imageI, len(images)))

  # Load the image; using opencv we'll usually have to provide uint8
  I = cv2.imread(os.path.join(source, image))
  if source_size > 0:
    I = resizeImage(I, source_size)

  # Convert to [0, 1]
  I = I.astype(np.float) / 255
  if grayscale:
    I = np.mean(I, axis=2)
    print(I.shape)

  # Call the algorithm and reconstruct the image using the palette
  IQ = quantize_algo(I, palette)
  R = reconstructImage(IQ, palette)
  
  # Store the height before we upsample
  # Sometimes it's hard to see the pixels and high-dpi screens screw up
  # Back in my day we were happy if our monitors' width had three digits
  heights[image] = I.shape[0]
  if target_size > 0:
    I, R = upscaleNN(I, target_size), upscaleNN(R, target_size)

  # As a sanity check, we'll write back whatever image we get (including
  # whether we grayscaled it)
  # Beware that you shouldn't tamper with images that you get passed!
  # Note the *255!
  I_path = os.path.join(target, image + "_orig.png")
  cv2.imwrite(I_path, (I * 255).astype(np.uint8))
  R_path = f"{image}_{algo_name}.png"
  R_path = os.path.join(target, R_path)
  cv2.imwrite(R_path, (R * 255).astype(np.uint8))


0/2


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations


1/2


In [55]:
# Run this cell if you are interested in visualizing all the results in one
# one shot within a webpage. It generates a file view.html that loads all the
# images in a table
view_algos = ["orig", algo_name]

with open(os.path.join(target, f"view_{algo_name}.html"), "w") as fh:
  fh.write("<html><body><table>")
  fh.write("<tr>")
  for algo in view_algos:
    fh.write(f"<td>{algo}</td>")
  fh.write("</tr>")
  for image in images:
    height = heights[image]
    fh.write("<tr>")
    for algo in view_algos:
      img_path = f"{image}_{algo}.png"
      fh.write(f"<td><img height='{height}' src='{img_path}'></td>")
    fh.write("</tr>")
  fh.write("</table></body></html>")
  fh.close()